### ISSUE TITLE
Support for Node 10 and 12

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-routes-stats#6]
The API for perf_hooks was changed in Node 10. We should support that as well.

**Comment by thearegee** [comment]
@mcollina I've started looking into this and using `PerformanceObserver` makes it a little tricker, have you thought about how you would like to implement this?

**Comment by mcollina** [comment]
I did and then totally forget, it should be simpler in Node 10, as it would not leaking memory by default.

**Comment by davealbert** [comment]
As LTS for 8 has ended, should this only support 10+ now?

**Comment by mcollina** [comment]
Yes!

Il giorno mar 10 mar 2020 alle ore 14:18 Dave Albert <
notifications@github.com> ha scritto:
